services:
  - type: web
    name: ocr-aadhar-app
    env: docker
    region: frankfurt
    plan: free # Note: Free tier might be slow for heavy ML models
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
